{% set name = "aedat" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aedat-{{ version }}.tar.gz
  sha256: 5256ef9cc5acf8f53b51d7b441aff17a6f9f9fd69c8ae0eba284e95a2b387262

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - maturin
  run:
    - python
    - numpy

test:
  imports:
    - aedat

about:
  home: https://github.com/neuromorphicsystems/aedat/
  summary: A fast AEDAT4 decoder with an underlying Rust implementation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
